version: "3.8"

services:
  tcp-iot-device:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROTOCOL: tcp
    depends_on:
      - tcp-iot-server
    command: node tcp/iot-device.js
    environment:
      SERVER_HOST: tcp-iot-server
      SERVER_PORT: 30000
  tcp-iot-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROTOCOL: tcp
    command: node tcp/iot-server.js
    environment:
      SERVER_HOST: tcp-iot-server
      SERVER_PORT: 30000
  mqtt-iot-device:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROTOCOL: mqtt
    depends_on:
      - tcp-iot-server
    command: node mqtt/iot-device.js
    environment:
      BROKER: mqtt://broker.hivemq.com
      DATA_TOPIC: mqtt/blog/examples/data
      CMD_REQ_TOPIC: mqtt/blog/examples/cmd/req
      CMD_RESP_TOPIC: mqtt/blog/examples/cmd/resp
      REGISTER_TOPIC: mqtt/blog/examples/register
  mqtt-iot-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROTOCOL: mqtt
    command: node mqtt/iot-server.js
    environment:
      BROKER: mqtt://broker.hivemq.com
      DATA_TOPIC: mqtt/blog/examples/data
      CMD_REQ_TOPIC: mqtt/blog/examples/cmd/req
      CMD_RESP_TOPIC: mqtt/blog/examples/cmd/resp
      REGISTER_TOPIC: mqtt/blog/examples/register
